berty/www.berty.tech

bertytech/config.yaml, bertytech/layouts/blog/single.html, bertytech/layouts/docs/single.html
=> Add "Edit on GitHub" links

bertytech/assets/img/avatar_aeddi.png, bertytech/content/blog/bluetooth-low-energy/2020-04-06-Berty-blogpost-Bluetooth-Low-Energy.jpg, bertytech/content/blog/bluetooth-low-energy/B1_hcXoDL.gif, bertytech/content/blog/bluetooth-low-energy/H1c6Dm9vU.jpg, bertytech/content/blog/bluetooth-low-energy/HkQ7J7iD8.gif, bertytech/content/blog/bluetooth-low-energy/HydFvfow8.png, bertytech/content/blog/bluetooth-low-energy/SkVml4jPI.jpg, bertytech/content/blog/bluetooth-low-energy/giphy.gif, bertytech/content/blog/bluetooth-low-energy/giphy2.gif, bertytech/content/blog/bluetooth-low-energy/index.md, bertytech/content/blog/bluetooth-low-energy/r17mW7jv8.jpg, bertytech/content/blog/bluetooth-low-energy/r1VGRZsv8.gif, bertytech/content/blog/bluetooth-low-energy/rkbQMNjvI.gif, bertytech/content/blog/bluetooth-low-energy/rkyZNGsP8.png, bertytech/data/authors.yml
My first contrib :)
I really wasn't sure what tags to put, feel free to correct.
=> feat: add 'Berty, Libp2p, and BLE' blog post

bertytech/data/authors.yml
Name: `Antoine Eddi` -> `Antoine`
Bio: `blablablabla` -> `Tech @ Berty`
:)
=> style: udpate aeddi's name and bio

README.md
Hi - just tried to build the site.
These are the requirements I noticed.
=> requirements for building the sites

bertytech/content/challenges/2-technical-challenges/index.md
BLE-related section added, a couple of sentences re-phrased to include more keywords
=> Section added, a couple of sentences changed

bertytech/content/challenges/1-goals/index.md
https://trello.com/c/nZdkifvq/637-add-sections-to-challenges
=> Adding more keywords

bertytech/Makefile, bertytech/post-build.sh, bertytech/validate-amp.js
Resolves #29 
Only validate AMP pages and ignore non-AMP pages
=> chore: Improve AMP validation

bertytech/assets/css/fontawesome.scss, bertytech/assets/css/style.scss, bertytech/layouts/partials/head.html
=> Relative css assets

bertytech/content/docs/community/index.md
[Become a backer] - doesn't lead anywhere, "backers" on which platform are implied? Haven't changed it yet, but this should either be removed or have a link placed in there.
=> Boutique link + text updated, Sponsors link, various grammar fixes

bertytech/config.yaml, bertytech/layouts/_default/_markup/render-image.html, bertytech/netlify.toml
=> Change to Lanczos resample filter for blog images

bertytech/content/challenges/2-technical-challenges/index.md
It may be misplaced, but there's no beginning quotation to `Making sure you are who you claim to be"`
=> Added missing quotation in challenges/constraints

bertytech/content/challenges/1-goals/index.md
"strengths" was misspelled as "strenghts"
=> Corrected misspelling in goals/index.md

bertytech/layouts/docs/single.html
=> Show last modified date on all docs

bertytech/assets/css/style.scss, bertytech/layouts/_default/list.html, bertytech/layouts/docs/list.html, bertytech/layouts/docs/single.html, bertytech/layouts/partials/btn_support_our_work.html
=> Add "Support our work" button

bertytech/content/blog/bluetooth-low-energy/index.md
=> fix: add more detail

.gitignore, AUTHORS, bertytech/assets/css/style.scss, bertytech/content/docs/protocol/B1onw7wdI.png, bertytech/content/docs/protocol/B1qIgVw_8.png, bertytech/content/docs/protocol/BJAQwQP_I.png, bertytech/content/docs/protocol/BJWLZR6vU.png, bertytech/content/docs/protocol/BkFkKBDOU.png, bertytech/content/docs/protocol/BymgCaaDI.png, bertytech/content/docs/protocol/H1jJ6fvdI.png, bertytech/content/docs/protocol/HJ9wKg0PL.png, bertytech/content/docs/protocol/HkAFBapv8.png, bertytech/content/docs/protocol/Hkn4kg0v8.png, bertytech/content/docs/protocol/Hks1bEvu8.png, bertytech/content/docs/protocol/Hy-d6h6wL.png, bertytech/content/docs/protocol/HyEDRMvO8.png, bertytech/content/docs/protocol/SJ6dgzaiU.png, bertytech/content/docs/protocol/SkWZnyPOU.png, bertytech/content/docs/protocol/SkXjmJRvL.png, bertytech/content/docs/protocol/SklLFmD_I.png, bertytech/content/docs/protocol/index.md, bertytech/content/docs/protocol/rJP2m-vO8.png, bertytech/content/docs/protocol/rkI4GWD_8.png, bertytech/content/docs/protocol/rkYDSaaDI.png, bertytech/content/docs/protocol/ry6qXApPU.png, bertytech/content/docs/protocol/ryrmDTpw8.png, bertytech/layouts/_default/_markup/render-image.html
Adds updated version of the protocol, still WIP and lack of review.
Will be improved later for:
- add details
- make certain passages clearer
- correcting errors / omissions
=> feat: update protocol with new version

bertytech/assets/css/style.scss, bertytech/postcss.config.js
Use CSS for padding code blocks as discussed in #76 
Closes #76
=> chore: Add padding to code blocks

bertytech/content/docs/community/index.md
fix shop url
Signed-off-by: pierreboc <31745588+pierreboc@users.noreply.github.com>
=> chore: update index.md

bertytech/netlify.toml, bertytech/package-lock.json, bertytech/package.json, bertytech/post-build.sh
Will be using this Netlify plugin to submit the sitemap instead (https://github.com/cdeleeuwe/netlify-plugin-submit-sitemap), so removing it from the post-build script.
=> Remove sitemap submission on postbuild

bertytech/layouts/partials/footer.html, bertytech/layouts/partials/navbar.html
=> fix: use absolute path for links on 404 page

bertytech/assets/css/style.scss
=> feat: add blockquote styling

bertytech/assets/css/style.scss, bertytech/layouts/partials/compare-messenger-apps.html
=> Make first column compare table fixed

bertytech/assets/js/amp-faq.js, bertytech/assets/js/amp-navbar.js
=> fix: workaround fix for amp-script classList

bertytech/assets/css/style.scss, bertytech/assets/js/amp-faq.js, bertytech/layouts/partials/block_faq.html
Example: https://deploy-preview-100--bertytech.netlify.app/faq#what-does-peer-to-peer-p2p-mean
=> Add FAQ anchors

bertytech/layouts/partials/nav_social.html, bertytech/layouts/shortcodes/display_section_social.html
=> Remove matrix

bertytech/assets/img/avatar_gfanton.png, bertytech/content/blog/gomobile-ipfs/gomobile-ipfs.jpg, bertytech/content/blog/gomobile-ipfs/index.md, bertytech/data/authors.yml
@cdeleeuwe can you modify and add "Guilhem" as the author of this blogpost? 
His info:
Name : Guilhem 
GitHub: gfanton
Twitter: https://twitter.com/gfanton42
For the thumbnail: you can use the one on his GitHub. 
Thanks :)
=> feat(blog): create gomobile-ipfs blogpost

bertytech/content/challenges/2-technical-challenges/index.md
just a small typo noticed when discovering your project today, in the spirit of #8 
looking forward to exploring more and helping with any test and development contributions
=> fix: minor typo fix

bertytech/config.yaml, bertytech/layouts/blog/single.html, bertytech/layouts/newsletter/single.html, bertytech/layouts/partials/discourse_comments.html, bertytech/layouts/partials/head.html
Resolves #49 
Example: https://deploy-preview-89--bertytech.netlify.app/blog/ngo-non-profit/
=> Add Discourse comments

bertytech/content/compare-table-apps/matrix.md
Signed-off-by: pierreboc <31745588+pierreboc@users.noreply.github.com>
Related to #103
* Open source can be filled 'True' (https://matrix.org/faq/#what-do-you-mean-by-open%3F: Matrix is also open source, meaning that we have released the source code of the reference servers, clients and services to the public domain under the Apache Licence v2, to encourage anyone and everyone to run their own servers and clients, and enhance them and contribute their enhancements as they see fit.)
* Considering [this post](https://matrix.org/blog/2020/06/02/introducing-p-2-p-matrix), we can switch Distributed from 'False' to 'Partially'.
* Since [2020-05-06](https://matrix.org/blog/2020/05/06/cross-signing-and-end-to-end-encryption-by-default-is-here), Matrix is is end-to-end encrypted by default for …
=> docs: update matrix.md

bertytech/content/compare-table-apps/session.md
I used [Sesssion white paper](https://arxiv.org/pdf/2002.04609.pdf) to fill out.
=> chore: add session.app

bertytech/static/apple-app-site-association
Fix app-site-association for universal link
Signed-off-by: clegirar <clemntgirard@gmail.com>
=> fix: app-site-association

bertytech/content/blog/best-password-manager/index.md, bertytech/content/blog/best-password-manager/password-manager.jpg
FYI: The cover will be changed on Monday ;)
=> feat(blog): create blogpost about password manager

bertytech/assets/css/style.scss
=> fix: homepage bg line

README.md
=> docs: Change Hugo to Hugo Extended in README.md

bertytech/go-get.csv
This might be only temporary (depending of if my PR is merged on [ipsn/go-libtor](https://github.com/ipsn/go-libtor))
=> Added go-libtor to the go-get.csv.

bertytech/config.yaml, bertytech/content/blog/2FA/index.fr.md, bertytech/layouts/blog/single.html, bertytech/layouts/partials/footer.html, bertytech/layouts/partials/head.html, bertytech/layouts/partials/navbar.html, bertytech/layouts/partials/rich-snippets/article-inner.html, bertytech/layouts/partials/rich-snippets/webpage-inner.html
Resolves #167 
**No translation (just copy of English version)**
https://deploy-preview-168--bertytech.netlify.app/fr/blog/2fa/
Canonical points to English page and language tags are "en"
**Translated page**
https://deploy-preview-168--bertytech.netlify.app/fr/blog/berty-at-fosdem-2020/
Canonical points to French page and language tags are "fr"
=> Improve i18n

bertytech/config.yaml, bertytech/layouts/shortcodes/display_section_contribute.html
=> Change contribute translations to crowdin url

bertytech/assets/css/style.scss, bertytech/assets/js/main.js, bertytech/layouts/shortcodes/display_section_id.md
addresses https://github.com/berty/berty/pull/2756
=> feat: support all QR codes

bertytech/content/support/books.png, bertytech/content/support/house.png, bertytech/content/support/index.fr.md, bertytech/content/support/index.id-id.md, bertytech/content/support/index.md, bertytech/content/support/phone.png, bertytech/layouts/_default/support.html
=> Add support page

bertytech/Makefile
Adds a command which disables all languages except English for faster development.
=> Add fastdev command

bertytech/layouts/shortcodes/display_section_contact_secure.html
So we can have a link: berty.tech/contact#secure
=> feat: add an id on contact secure section to have an anchor link

bertytech/layouts/partials/section_values.html
minor typo fix, from solution focus to solution focused. was just looking into cool ipfs products and stumbled upon this.
pretty sure i'm in line with issue [#8](https://github.com/berty/www.berty.tech/issues/8)
not sure i'm quite capable enough to help with the actual code but i'll give it a shot :)
=> small typo fix on section_value.html

bertytech/content/compare-table-apps/scuttlebut.md
Signed-off-by: pierreboc <31745588+pierreboc@users.noreply.github.com>
=> Update and rename skuttlebut.md to scuttlebut.md

bertytech/netlify.toml, bertytech/package-lock.json, bertytech/package.json, bertytech/plugins/verify-pages/index.js, bertytech/plugins/verify-pages/manifest.yml
Add a Netlify plugin that checks if all pages are generated. 
Resolves #256
=> Add verify pages plugin

bertytech/go-get.csv
Signed-off-by: D4ryl00 <d4ryl00@gmail.com>
=> feat: add redirection to future weshnet repo

bertytech/layouts/partials/navbar.html
Fixed English text
protocole -> protocol
=> fix: (navbar) Update English text

bertytech/layouts/jobs/list.html
=> chore: remove job listing

bertytech/assets/img/avatar_lfgaming.png, bertytech/content/newsletter/news-72/index.md, bertytech/data/authors.yml
Related to feature request #410
=> add LFGaming to the authors for the newsletter

bertytech/content/newsletter/news-73/index.md
Changed the name GnoSocial to dSocial in newsletter 73
=> Change GnoSocial to the new name dSocial

bertytech/content/newsletter/news-73/index.md
replaced one last GnoSocial reference with dSocial
=> Minor Newsletter 73 Update index.md
